default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  adapter: postgresql
  database: my_localappdatabase_test

production:
  adapter: postgresql
  database: my_localappdatabase_production
  username:
  password:
